"""
Fixture Model - Represents scheduled matches in competitions
"""

from datetime import datetime
from typing import Optional
from sqlalchemy import (
    String, Integer, CheckConstraint, Index, 
    DateTime, ForeignKey, Enum as SQLEnum
)
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func
import enum

from app.core.database import Base


class FixtureStatus(str, enum.Enum):
    """Fixture status enumeration"""
    SCHEDULED = "scheduled"
    COMPLETED = "completed"
    POSTPONED = "postponed"
    CANCELLED = "cancelled"


class Fixture(Base):
    """
    Fixture model representing scheduled matches in competitions.
    
    Fixtures are generated by the Competition_Engine at the start of each season
    and link competitions to matches. Each fixture represents a scheduled match
    between two clubs in a specific competition on a specific matchday/round.
    
    The Competition_Engine:
    - Generates full season fixture lists at season start
    - Simulates non-player-managed matches using Game_Engine and AI_Manager
    - Updates fixture status after match completion
    - Maintains live league tables based on fixture results
    - Checks player availability (injuries, suspensions) before matches
    
    Fixture Scheduling:
    - Domestic league: 38 matchdays (20 clubs, home and away)
    - Domestic cup: Knockout rounds (Round of 64, 32, 16, QF, SF, Final)
    - Continental cup: Group stage (6 matchdays) + knockout rounds
    
    Attributes:
        id: Primary key, auto-increment
        
        Foreign Keys:
            competition_id: Foreign key to Competition
            home_club_id: Foreign key to home Club
            away_club_id: Foreign key to away Club
            match_id: Optional foreign key to Match (set after match is played)
        
        Fixture Details:
            matchday: Matchday/round number (1-based)
            round_name: Optional round name for cups (e.g., "Quarter Final", "Semi Final")
            scheduled_date: Scheduled date and time for the fixture
        
        Fixture Status:
            status: Current fixture status (scheduled, completed, postponed, cancelled)
        
        Timestamps:
            created_at: Timestamp when fixture was created
            updated_at: Timestamp when fixture was last updated
    """
    
    __tablename__ = "fixtures"
    
    # Primary key
    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    
    # Foreign Keys
    competition_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("competitions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="Foreign key to Competition"
    )
    
    home_club_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("clubs.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
        comment="Foreign key to home Club"
    )
    
    away_club_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("clubs.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
        comment="Foreign key to away Club"
    )
    
    match_id: Mapped[Optional[int]] = mapped_column(
        Integer,
        ForeignKey("matches.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
        comment="Optional foreign key to Match (set after match is played)"
    )
    
    # Fixture Details
    matchday: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        index=True,
        comment="Matchday/round number (1-based)"
    )
    
    round_name: Mapped[Optional[str]] = mapped_column(
        String(100),
        nullable=True,
        comment="Optional round name for cups (e.g., Quarter Final, Semi Final)"
    )
    
    scheduled_date: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        index=True,
        comment="Scheduled date and time for the fixture"
    )
    
    # Fixture Status
    status: Mapped[str] = mapped_column(
        SQLEnum(FixtureStatus),
        nullable=False,
        default=FixtureStatus.SCHEDULED,
        server_default=FixtureStatus.SCHEDULED.value,
        index=True,
        comment="Current fixture status (scheduled, completed, postponed, cancelled)"
    )
    
    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="Timestamp when fixture was created"
    )
    
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
        comment="Timestamp when fixture was last updated"
    )
    
    # Relationships (will be populated when related models are created)
    # competition: Mapped["Competition"] = relationship("Competition", back_populates="fixtures")
    # home_club: Mapped["Club"] = relationship("Club", foreign_keys=[home_club_id], back_populates="home_fixtures")
    # away_club: Mapped["Club"] = relationship("Club", foreign_keys=[away_club_id], back_populates="away_fixtures")
    # match: Mapped[Optional["Match"]] = relationship("Match", back_populates="fixture")
    
    # Check constraints and indexes
    __table_args__ = (
        # Matchday constraint (> 0)
        CheckConstraint('matchday > 0', name='check_matchday_positive'),
        
        # Home and away clubs must be different
        CheckConstraint('home_club_id != away_club_id', name='check_different_clubs'),
        
        # Performance indexes
        Index('idx_fixtures_competition_id', 'competition_id'),
        Index('idx_fixtures_home_club_id', 'home_club_id'),
        Index('idx_fixtures_away_club_id', 'away_club_id'),
        Index('idx_fixtures_match_id', 'match_id'),
        Index('idx_fixtures_matchday', 'matchday'),
        Index('idx_fixtures_scheduled_date', 'scheduled_date'),
        Index('idx_fixtures_status', 'status'),
        # Composite indexes for common queries
        Index('idx_fixtures_competition_matchday', 'competition_id', 'matchday'),
        Index('idx_fixtures_competition_status', 'competition_id', 'status'),
        Index('idx_fixtures_club_date', 'home_club_id', 'away_club_id', 'scheduled_date'),
        Index('idx_fixtures_date_status', 'scheduled_date', 'status'),
        # Unique constraint: same clubs cannot play twice on same matchday in same competition
        Index('idx_fixtures_unique_matchday', 'competition_id', 'matchday', 'home_club_id', 'away_club_id', unique=True),
    )
    
    def __repr__(self) -> str:
        """String representation of Fixture"""
        return (
            f"<Fixture(id={self.id}, "
            f"competition_id={self.competition_id}, "
            f"home_club_id={self.home_club_id} vs away_club_id={self.away_club_id}, "
            f"matchday={self.matchday}, "
            f"status={self.status})>"
        )
    
    def to_dict(self) -> dict:
        """
        Convert Fixture model to dictionary.
        
        Returns:
            dict: Dictionary representation of the fixture with all attributes
        """
        return {
            "id": self.id,
            "competition_id": self.competition_id,
            "home_club_id": self.home_club_id,
            "away_club_id": self.away_club_id,
            "match_id": self.match_id,
            # Fixture Details
            "details": {
                "matchday": self.matchday,
                "round_name": self.round_name,
                "scheduled_date": self.scheduled_date.isoformat() if self.scheduled_date else None,
            },
            # Status
            "status": self.status,
            # Timestamps
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }
    
    def is_scheduled(self) -> bool:
        """
        Check if fixture is scheduled.
        
        Returns:
            bool: True if scheduled, False otherwise
        """
        return self.status == FixtureStatus.SCHEDULED
    
    def is_completed(self) -> bool:
        """
        Check if fixture is completed.
        
        Returns:
            bool: True if completed, False otherwise
        """
        return self.status == FixtureStatus.COMPLETED
    
    def is_postponed(self) -> bool:
        """
        Check if fixture is postponed.
        
        Returns:
            bool: True if postponed, False otherwise
        """
        return self.status == FixtureStatus.POSTPONED
    
    def is_cancelled(self) -> bool:
        """
        Check if fixture is cancelled.
        
        Returns:
            bool: True if cancelled, False otherwise
        """
        return self.status == FixtureStatus.CANCELLED
    
    def has_match(self) -> bool:
        """
        Check if fixture has an associated match.
        
        Returns:
            bool: True if match_id is set, False otherwise
        """
        return self.match_id is not None
    
    def complete_fixture(self, match_id: int) -> None:
        """
        Mark fixture as completed and link to match.
        
        Args:
            match_id: ID of the completed match
        """
        self.match_id = match_id
        self.status = FixtureStatus.COMPLETED
    
    def postpone_fixture(self, new_date: datetime) -> None:
        """
        Postpone fixture to a new date.
        
        Args:
            new_date: New scheduled date for the fixture
        """
        self.scheduled_date = new_date
        self.status = FixtureStatus.POSTPONED
    
    def cancel_fixture(self) -> None:
        """Cancel fixture."""
        self.status = FixtureStatus.CANCELLED
    
    def reschedule_fixture(self, new_date: datetime) -> None:
        """
        Reschedule fixture to a new date and reset status to scheduled.
        
        Args:
            new_date: New scheduled date for the fixture
        """
        self.scheduled_date = new_date
        self.status = FixtureStatus.SCHEDULED
    
    def is_past_scheduled_date(self) -> bool:
        """
        Check if fixture's scheduled date has passed.
        
        Returns:
            bool: True if scheduled date is in the past, False otherwise
        """
        return datetime.now(self.scheduled_date.tzinfo) > self.scheduled_date
    
    def get_days_until_fixture(self) -> int:
        """
        Calculate days until fixture.
        
        Returns:
            int: Number of days until fixture (negative if in the past)
        """
        now = datetime.now(self.scheduled_date.tzinfo)
        delta = self.scheduled_date - now
        return delta.days
